name: Release Plugin

on:
  push:
    tags:
      - 'v*'  # 当推送以 v 开头的 tag 时触发

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Get Version from Tag
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Update Version in build.gradle.kts
        run: |
          sed -i "s/version = \".*\"/version = \"${{ steps.get_version.outputs.version }}\"/" build.gradle.kts

      - name: Build Plugin
        run: ./gradlew buildPlugin
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PRIVATE_KEY_PASSWORD: ${{ secrets.PRIVATE_KEY_PASSWORD }}
          CERTIFICATE_CHAIN: ${{ secrets.CERTIFICATE_CHAIN }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          files: build/distributions/easy-translate-${{ steps.get_version.outputs.version }}.zip
          draft: false
          prerelease: false
          generate_release_notes: true
          body: |
            ### Changes in this release:
            - Initial release of Easy Translate Plugin
            - Support for multiple translation engines (Baidu, Youdao, Google)
            - Custom dictionary feature
            - Variable name suggestions
            - Text case conversion tools
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Plugin
        run: ./gradlew publishPlugin
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PRIVATE_KEY_PASSWORD: ${{ secrets.PRIVATE_KEY_PASSWORD }}
          CERTIFICATE_CHAIN: ${{ secrets.CERTIFICATE_CHAIN }}
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }} 