name: Release Plugin

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Get Version
        id: get_version
        run: |
          VERSION=$(grep 'version = ' build.gradle.kts | cut -d'"' -f2)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Delete existing tag if exists
        run: |
          TAG_NAME="v${{ steps.get_version.outputs.version }}"
          git push origin :refs/tags/$TAG_NAME || true

      - name: Build Plugin
        run: ./gradlew buildPlugin
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PRIVATE_KEY_PASSWORD: ${{ secrets.PRIVATE_KEY_PASSWORD }}
          CERTIFICATE_CHAIN: ${{ secrets.CERTIFICATE_CHAIN }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: Release v${{ steps.get_version.outputs.version }}
          files: build/distributions/easy-translate-${{ steps.get_version.outputs.version }}.zip
          draft: false
          prerelease: false
          generate_release_notes: true
          body: |
            🔄 This release replaces the previous version with the same number.
            
            ### Changes in this update:
            - Updated plugin build
            - Refreshed release assets
          
          # 允许覆盖已存在的 release
          replace_artifacts_if_exist: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Plugin
        run: ./gradlew publishPlugin
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PRIVATE_KEY_PASSWORD: ${{ secrets.PRIVATE_KEY_PASSWORD }}
          CERTIFICATE_CHAIN: ${{ secrets.CERTIFICATE_CHAIN }}
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }} 